Repository ltapmaracanau/plaforedu, pull requests merged in 2024-07, with the labels that each got.

#328 feat: Adicionando termos de privacidade e cookies
  src/components/privacyTerms/TermCookiesModal.jsx
  src/components/privacyTerms/TermPrivacyModal.jsx
  src/components/user-settings/FormativeTrailsRegister.jsx
  src/routes/CustomRoutes.jsx
Labels: feature, fix

#329 Feat/new faq layout
  src/pages/FAQ.jsx
  src/pages/faq.css
Labels: feature

#330 feat: Visualização e edição de documentos
  src/components/documents/DocumentsVisualization.jsx
  src/components/documents/ViewAllDocumentsModal.jsx
  src/components/user-settings/DocumentRegister.jsx
  src/components/user-settings/DocumentsList.jsx
  src/components/user-settings/EvaluateChanges.jsx
  src/components/user-settings/StudyPlans.jsx
  src/components/user-settings/UsersList.jsx
  src/model/adm-model.js
  src/model/documents-model.js
  src/model/index.js
  src/pages/HistoryPlaforPage.jsx
  src/pages/SettingsPage.jsx
  src/routes/CustomRoutes.jsx
  src/schemas/registers/registersSchema.js
  src/services/documents-service.js
  src/services/index.js
Labels: feature

#331 hotfix: Corrigindo modal adicionar equivalentes
  src/components/filter-components/TableSelectCourses.jsx
  src/pages/HomePage.jsx
  src/pages/homepage.css
Labels: bug

#332 Layout: Ajustando erros de layouts homepage e outras páginas
  .gitignore
  package-lock.json
  src/components/CourseModalVisualization.jsx
  src/components/user-settings/DocumentsList.jsx
  src/components/user-settings/FormativeTrailsRegister.jsx
  src/components/user-settings/ListSearchLogs.jsx
  src/components/user-settings/UsersList.jsx
  src/model/users-model.js
  src/pages/HomePage.jsx
  src/pages/NotFound.jsx
  src/routes/CustomRoutes.jsx
  src/services/adm-service.js
  yarn.lock
Labels: bug, layout

#338 refact: Refatorando paginações de todos os cadastros
  src/components/CourseModalVisualization.jsx
  src/components/Finder.jsx
  src/components/SideFilter.jsx
  src/components/fields/DebounceSelect.jsx
  src/components/filter-components/TableAddTrailStudyPlan.jsx
  src/components/filter-components/TableSelectCourses.jsx
  src/components/user-settings/CategCompList.jsx
  src/components/user-settings/CompList.jsx
  src/components/user-settings/CompRegister.jsx
  src/components/user-settings/CourseRegister.jsx
  src/components/user-settings/CoursesList.jsx
  src/components/user-settings/FormativeTrailsList.jsx
  src/components/user-settings/FormativeTrailsRegister.jsx
  src/components/user-settings/InstitutionRegister.jsx
  src/components/user-settings/InstitutionsList.jsx
  src/components/user-settings/StudyPlanRegister.jsx
  src/components/user-settings/StudyPlanView.jsx
  src/components/user-settings/SubtemaRegister.jsx
  src/components/user-settings/SubtemasList.jsx
  src/components/user-settings/TemasList.jsx
  src/components/visualizacao-cursos/CoursesListVisualization.jsx
  src/components/visualizacao-cursos/CytoscapeVisualization.jsx
  src/helpers/reformuladorDeElementosCytoscape.js
  src/model/accessibilities-model.js
  src/model/adm-model.js
  src/model/competencies-model.js
  src/model/courses-model.js
  src/model/institutions-model.js
  src/model/themes-model.js
  src/model/trilhas-model.js
  src/pages/AboutPage.jsx
  src/pages/CoursesPage.jsx
  src/pages/HomePage.jsx
  src/routes/CustomRoutes.jsx
  src/schemas/registers/registersSchema.js
  src/services/comp-service.js
  src/services/institution-service.js
  src/services/themes-service.js
  src/services/trails-service.js
Labels: fix

#337 Feat/logs courses trails
  src/components/TrailModalVisualization.jsx
  src/components/user-settings/CompRegister.jsx
  src/components/user-settings/CourseRegister.jsx
  src/components/user-settings/HistoricoItens.jsx
  src/components/user-settings/SubtemaRegister.jsx
  src/components/user-settings/SystemLog.jsx
  src/model/adm-model.js
  src/model/trilhas-model.js
  src/pages/HomePage.jsx
  src/services/adm-service.js
Labels: feature

#339 feat: Link política de privacidade no footer
  src/components/footer/FooterGov.jsx
  src/components/privacyTerms/TermPrivacyModal.jsx
Labels: feature

#340 layout: Ajustando layout sobre e historico
  src/pages/AboutPage.jsx
  src/pages/AboutPage.module.css
  src/pages/HistoryPlaforPage.jsx
Labels: layout

#342 layout: Novo Layout Fale Conosco
  src/components/user-settings/DocumentRegister.jsx
  src/components/user-settings/DocumentsList.jsx
  src/pages/FaleConosco.jsx
Labels: layout

#341 feat: Progresso no plano de estudo
  src/components/privacyTerms/TermConsentLogin.jsx
  src/components/user-settings/StudyPlanView.jsx
  src/components/user-settings/StudyPlans.jsx
  src/model/adm-model.js
  src/model/study-plans-model.js
  src/pages/Login.jsx
  src/routes/CustomRoutes.jsx
  src/services/study-plans-service.js
  src/services/users-service.js
Labels: feature

#343 fix: mudado nome de plano de estudo para plano de desenvolvimento
  src/components/filter-components/TableAddTrailStudyPlan.jsx
  src/components/header/HeaderHome.jsx
  src/components/user-settings/StudyPlanRegister.jsx
  src/components/user-settings/StudyPlanView.jsx
  src/components/user-settings/StudyPlans.jsx
  src/pages/SettingsPage.jsx
  src/schemas/registers/registersSchema.js
Labels: frontend, fix

#344 fix: Loading infinito ao entrar sem aceitar uso de cookies
  src/components/user-settings/CategCompList.jsx
  src/components/user-settings/CompList.jsx
  src/components/user-settings/CoursesList.jsx
  src/components/user-settings/DocumentsList.jsx
  src/components/user-settings/FormativeTrailsList.jsx
  src/components/user-settings/FormativeTrailsRegister.jsx
  src/components/user-settings/InstitutionsList.jsx
  src/components/user-settings/StudyPlanView.jsx
  src/components/user-settings/StudyPlans.jsx
  src/components/user-settings/SubtemasList.jsx
  src/components/user-settings/TemasList.jsx
  src/pages/Denied.jsx
  src/pages/HistoryPlaforPage.jsx
  src/pages/Login.jsx
  src/pages/SettingsPage.jsx
  src/routes/CustomRoutes.jsx
  src/schemas/registers/updatePasswordSchema.js
Labels: fix
